# **Problema de las montañas de Alicante**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import folium ##Para los mapas interactivos
import random

In [2]:
datos=pd.read_csv("Montañas.csv")
datos['Altitud'] = datos['Altitud'].str.replace(' m', '',regex=False)
nueva_fila={"Montaña":"Santa_Barbara","Altitud":186,"Dificultad":7,"Distancia_por_carretera (km)":31}
datos=pd.concat([datos,pd.DataFrame([nueva_fila])],ignore_index=True)
datos

           Montaña Altitud  Dificultad  Distancia_por_carretera (km)
0           Aitana   1.558           4                            24
1     Puig_Campana   1.406           8                            25
2           Ponoig   1.181           8                            34
3           Bernia   1.128           7                            19
4   Peñon_de_Ifach     332           5                            52
5   Pla_de_la_Casa   1.379           7                            31
6       Montcabrer   1.390           5                            54
7           Maigmo   1.296           6                            28
8              Cid   1.296           6                            35
9      Cabeço_d'Or   1.210           6                            40
10   Santa_Barbara     186           7                            31

In [330]:
matriz = pd.read_excel("Matriz_Distancias_Alicante.xlsx",index_col=0)
print(matriz.index)
print("\n")
print(matriz.columns)
print(matriz.at["Puig Campana","Cabeçó d'Or"])

Index(['Aitana', 'Puig Campana', 'Ponoig', 'Bernia', 'Peñón de Ifach',
       'Pla de la Casa', 'Montcabrer', 'Maigmó', 'El Cid', 'Cabeçó d'Or',
       'Alicante', 'El Montgó', 'El Menejador', 'Sierra Helada', 'El Picacho',
       'La Muela', 'Cruz de Callosa', 'Mallada del Llop', 'Sierra de Segària',
       'Sierra de Oltà', 'El Reconco', 'Sierra de Fontcalent',
       'Ermita de Orito', 'Peña Migjorn'],
      dtype='str')


Index(['Aitana', 'Puig Campana', 'Ponoig', 'Bernia', 'Peñón de Ifach',
       'Pla de la Casa', 'Montcabrer', 'Maigmó', 'El Cid', 'Cabeçó d'Or',
       'Alicante', 'El Montgó', 'El Menejador', 'Sierra Helada', 'El Picacho',
       'La Muela', 'Cruz de Callosa', 'Mallada del Llop', 'Sierra de Segària',
       'Sierra de Oltà', 'El Reconco', 'Sierra de Fontcalent',
       'Ermita de Orito', 'Peña Migjorn'],
      dtype='str')
31.3

# **Grafo Disperso de las montañas**

In [9]:
matriz = pd.read_excel("matriz 2.xlsx",index_col=0)
matriz = matriz.replace(10000, float('inf'))
print(matriz.at["Alicante","Maigmo"])
print(matriz.at["Sierra de Olta","Peñon de Ifach"])

25.4
5.6

# **Grafo de los puertos de bici**

In [5]:
matriz=pd.read_excel("puertos_bici.xlsx",index_col=0)
matriz=matriz.replace(10000,float("inf"))
matriz.at["La Carrasqueta","Benifallim"]
matriz

,Aitana (Tudons),La Carrasqueta,Benifallim,Confrides,El Canalís,Torremanzanas,Tibi,Coll de Rates,Val de Ebo,Tàrbena,...,Font Roja,Rebolcat,Oronet (Alicante),Puig Campana,Tollos,Balcón de Alicante,Maigmó,Hoya de la Carrasca,Vall d'Alcalà,El Picacho
Aitana (Tudons),0.0,inf,18.0,12.0,inf,inf,inf,inf,inf,inf,...,22.0,inf,inf,inf,inf,inf,inf,5.0,inf,inf
La Carrasqueta,inf,0.0,14.0,inf,inf,12.0,20.0,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,15.0,inf,inf,inf
Benifallim,18.0,14.0,0.0,inf,inf,10.0,inf,inf,inf,inf,...,12.0,15.0,inf,inf,inf,inf,inf,inf,inf,inf
Confrides,12.0,inf,inf,0.0,inf,inf,inf,inf,inf,20.0,...,inf,inf,inf,22.0,inf,inf,inf,inf,inf,inf
El Canalís,inf,inf,inf,inf,0.0,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
Torremanzanas,inf,12.0,10.0,inf,inf,0.0,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
Tibi,inf,20.0,inf,inf,inf,inf,0.0,inf,inf,inf,...,inf,inf,inf,inf,inf,8.0,10.0,inf,inf,inf
Coll de Rates,inf,inf,inf,inf,inf,inf,inf,0.0,18.0,6.0,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
Val de Ebo,inf,inf,inf,inf,inf,inf,inf,18.0,0.0,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,12.0,inf
Tàrbena,inf,inf,inf,20.0,inf,inf,inf,6.0,inf,0.0,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
Miserat,inf,inf,inf,inf,inf,inf,inf,inf,10.0,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
Sierra de Bernia,inf,inf,inf,inf,inf,inf,inf,12.0,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
Cumbre del Sol,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
Cap de la Nau,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
Guadalest,inf,inf,inf,15.0,inf,inf,inf,inf,inf,14.0,...,inf,inf,inf,18.0,inf,inf,inf,inf,inf,inf
Monte Pego,inf,inf,inf,inf,inf,inf,inf,inf,15.0,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
Xorret de Catí,inf,inf,inf,inf,15.0,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,8.0,inf,inf,inf,20.0
El Reconco,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,18.0
Port de l'Albiol,inf,inf,15.0,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,20.0,inf,inf,inf,inf,inf
Puerto de Biar,inf,inf,inf,inf,10.0,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
Font Roja,22.0,inf,12.0,inf,inf,inf,inf,inf,inf,inf,...,0.0,8.0,inf,inf,inf,inf,inf,inf,inf,inf
Rebolcat,inf,inf,15.0,inf,inf,inf,inf,inf,inf,inf,...,8.0,0.0,inf,inf,inf,inf,inf,inf,inf,inf
Oronet (Alicante),inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,0.0,inf,inf,inf,20.0,inf,inf,inf
Puig Campana,inf,inf,inf,22.0,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,0.0,inf,inf,inf,inf,inf,inf
Tollos,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,0.0,inf,inf,15.0,8.0,inf
Balcón de Alicante,inf,inf,inf,inf,inf,inf,8.0,inf,inf,inf,...,inf,inf,inf,inf,inf,0.0,12.0,inf,inf,inf
Maigmó,inf,15.0,inf,inf,inf,inf,10.0,inf,inf,inf,...,inf,inf,20.0,inf,inf,12.0,0.0,inf,inf,inf
Hoya de la Carrasca,5.0,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,15.0,inf,inf,0.0,inf,inf
Vall d'Alcalà,inf,inf,inf,inf,inf,inf,inf,inf,12.0,inf,...,inf,inf,inf,inf,8.0,inf,inf,inf,0.0,inf
El Picacho,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,0.0

# **Mapa interactivo de las montañas**

In [6]:
coordenadas= {
    "Aitana": [38.6483, -0.2644],
    "Puig Campana": [38.5914, -0.1969],
    "Ponoig": [38.6111, -0.1556],
    "Bernia": [38.6636, -0.0436],
    "Peñón de Ifach": [38.6347, 0.0747],
    "Pla de la Casa": [38.6833, -0.3167],
    "Montcabrer": [38.7667, -0.4667],
    "Maigmó": [38.4833, -0.6167],
    "El Cid": [38.4842, -0.7417],
    "Cabeçó d'Or": [38.5167, -0.4167],
    "El Montgó": [38.8083, 0.1167],          
    "El Menejador": [38.6475, -0.5461],      
    "Sierra Helada": [38.5447, -0.0767],     
    "El Picacho": [38.2638, -0.8953],        # Sierra de Crevillente
    "La Muela": [38.1078, -0.9689],          
    "Cruz de Callosa": [38.1225, -0.8797],
    "Mallada del Llop": [38.6828, -0.2331],  
    "Sierra de Segària": [38.8239, 0.0039],  # El "gigante de piedra" de la Marina
    "Sierra de Oltà": [38.6521, 0.0156],     
    "El Reconco": [38.6186, -0.7383],
    "Sierra de Fontcalent": [38.3586, -0.5894], 
    "Ermita de Orito": [38.3842, -0.7225],      
    "Peña Migjorn": [38.5283, -0.5333],         
    "Alicante": [38.3453,-0.4831]
}

##Creo el mapa interactivo desde mi punto central
m = folium.Map(location=coordenadas["Alicante"], zoom_start=10,tiles="OpenStreetMap")
##Relleno el mapa con los puntos de mi diccionario
for nombre, coords in coordenadas.items():
    folium.Marker(location=coords, tooltip=nombre).add_to(m)
##Lo guardo como archivo html para visualizarlo en cualquier navegador
m.save("mapa_interactivo.html")

# **Mapa Interactivo de los puertos**

In [7]:
coordenadas_puertos= {
    "Aitana (Tudons)": [38.6482, -0.2642], # Paso de la CV-770 (Correcto)
    "La Carrasqueta": [38.5866, -0.5042],  # Mirador/Paso superior CV-800
    "Benifallim": [38.6536, -0.3958],      # Puerto de Benifallim CV-785
    "Confrides": [38.6830, -0.2670],       # Puerto de Confrides CV-70
    "El Canalís": [38.6822, -0.6725],      # Paso de Onil a Bañeres
    "Torremanzanas": [38.5847, -0.4192],   # Puerto de Benifallim/Torremanzanas
    "Tibi": [38.5303, -0.5978],            # Puerto de Tibi
    "Coll de Rates": [38.7249,-0.0764],   # Cima de la carretera CV-715
    "Val de Ebo": [38.8058, -0.1589],      # Puerto de Ebo
    "Tàrbena": [38.6942, -0.1222],         # Coll de Sa Creueta (Tàrbena)
    "Miserat": [38.8332,-0.1531],         # Acceso por carretera (no la antena cima)
    "Sierra de Bernia": [38.6210, -0.0450],# Casas de Bernia (donde termina el asfalto)
    "Cumbre del Sol": [38.7180, 0.1520],   # Parking superior (Puig Llorença)
    "Cap de la Nau": [38.7300, 0.2200],    # Final de la carretera del Faro
    "Guadalest": [38.6767, -0.1983],       # Paso del pueblo/embalse
    "Monte Pego": [38.8250, -0.0620],      # Cima de la urbanización
    "Xorret de Catí": [38.5285, -0.6869],  # Paso de la cresta (Escalinata)
    "El Reconco": [38.6186, -0.7383],      # Final del asfalto junto a antenas
    "Port de l'Albiol": [38.6756, -0.4439],# Alto de l'Albiol
    "Puerto de Biar": [38.6294, -0.7658],  # CV-799
    "Font Roja": [38.6608, -0.5372],       # Santuario (final de carretera)
    "Font de Partegat": [38.6574,-0.2446],        
    "Oronet (Alicante)": [38.5642, -0.2458],# Alto de Finestrat/Sella
    "Puig Campana": [38.5830, -0.2150],    # Font del Molí (Base accesible) *
    "Tollos": [38.7561, -0.2747],          # Puerto de Tollos
    "Balcón de Alicante": [38.4983, -0.6289],# Área recreativa (carretera)
    "Maigmó": [38.4833, -0.6167],          # Aparcamiento Maigmó
    "Hoya de la Carrasca": [38.6850, -0.2950], # Paso montaña
    "Vall d'Alcalà": [38.7944, -0.2458],   # Puerto de Margarida/Alcalà
    "El Picacho": [38.2610, -0.8870]       # Puerto de la Pila (carretera)
}

# Creamos el mapa centrado en una zona intermedia de la montaña de Alicante
m = folium.Map(location=[38.6, -0.3], zoom_start=10, tiles="OpenStreetMap")

# Rellenamos el mapa con iconos de bicicleta
for nombre, coords in coordenadas_puertos.items():
    folium.Marker(
        location=coords,
        tooltip=nombre,
        popup=f"Puerto: {nombre}",
        icon=folium.Icon(color="blue", icon="bicycle", prefix="fa") # Icono de bici (FontAwesome)
    ).add_to(m)

# Guardamos el mapa interactivo
m.save("mapa_puertos_alicante.html")

# **Vecindad cercana**

In [11]:
camino=["Alicante"]
kilometraje=0
while len(camino)<len(matriz):
    kilom=10000 ##variable inicial con kilómetros
    for nueva in matriz.columns:
        if nueva not in camino:
            kil=matriz.at[camino[-1],nueva]
            if kil<kilom:
                kilom=kil
                sig=nueva
    camino.append(sig)
    kilometraje+=kilom
print("El camino sería:",camino)
print("\n")
print(f"Habríamos recorrido {kilometraje} km y habríamos hecho {len(camino)} paradas")

tipo="gasolina 95"
consumo=8
if tipo=="diesel":
    print(f"Te vas a gastar {kilometraje/100*consumo*1.729} $")
if tipo=="gasolina 95":
    print(f"Te vas a gastar {kilometraje/100*consumo*1.64} $")

El camino sería: ['Alicante', 'Sierra de Fontcalent', 'Ermita de Orito', 'El Cid', 'Maigmo', 'Peña Migjorn', "Cabeco d'Or", 'Aitana', 'Mallada del Llop', 'Pla de la Casa', 'Montcabrer', 'El Menejador', 'El Reconco', 'El Reconco', 'El Reconco', 'El Reconco', 'El Reconco', 'El Reconco', 'El Reconco', 'El Reconco', 'El Reconco', 'El Reconco', 'El Reconco', 'El Reconco']


Habríamos recorrido 110148.5 km y habríamos hecho 24 paradas
Te vas a gastar 14451.483199999997 $

# **Algoritmo de Prim**

In [17]:
camin=["Alicante"]
camino=[]
kilometraje=0
while len(camin)<len(matriz):
    kilom=1000 ##Variable iniciadora
    for nueva in matriz.columns:
        if nueva not in camin:
            for elemento in camin:
                kil=matriz.at[elemento,nueva]
                if kil<kilom:
                    kilom=kil
                    elem=elemento
                    nuev=nueva
    camin.append(nuev)
    camino.append([elem,nuev])
    kilometraje+=kilom
print("El camino sería:",camin,f"y por tanto haríamos {len(camin)} paradas")
print("El árbol de mínima expansión sería", *camino)
print("La longitud total de este árbol sería:", kilometraje,"km")

El camino sería: ['Alicante', 'Sierra de Fontcalent', 'Ermita de Orito', 'El Cid', 'Maigmo', 'Peña Migjorn', 'El Reconco', 'El Picacho', "Cabeco d'Or", 'Aitana', 'Mallada del Llop', 'Pla de la Casa', 'Puig Campana', 'Ponoig', 'Sierra Helada', 'Bernia', 'Sierra de Olta', 'Peñon de Ifach', 'Montcabrer', 'El Menejador', 'Cruz de Callosa', 'La Muela', 'El Montgo', 'Sierra de Segaria'] y por tanto haríamos 24 paradas
El árbol de mínima expansión sería ['Alicante', 'Sierra de Fontcalent'] ['Sierra de Fontcalent', 'Ermita de Orito'] ['Ermita de Orito', 'El Cid'] ['El Cid', 'Maigmo'] ['Maigmo', 'Peña Migjorn'] ['El Cid', 'El Reconco'] ['Ermita de Orito', 'El Picacho'] ['Peña Migjorn', "Cabeco d'Or"] ["Cabeco d'Or", 'Aitana'] ['Aitana', 'Mallada del Llop'] ['Mallada del Llop', 'Pla de la Casa'] ['Aitana', 'Puig Campana'] ['Puig Campana', 'Ponoig'] ['Ponoig', 'Sierra Helada'] ['Ponoig', 'Bernia'] ['Bernia', 'Sierra de Olta'] ['Sierra de Olta', 'Peñon de Ifach'] ['Pla de la Casa', 'Montcabrer'] ['Montcabrer', 'El Menejador'] ['El Picacho', 'Cruz de Callosa'] ['Cruz de Callosa', 'La Muela'] ['Sierra de Olta', 'El Montgo'] ['El Montgo', 'Sierra de Segaria']
La longitud total de este árbol sería: 270.5 km

# **Single Source Shortest Path**

In [15]:
camin=["Alicante"]
camino=[]
distancia_acumulada = {col: 0 if col == "Alicante" else np.inf for col in matriz.columns}
total=0
while len(camin)<len(matriz):
    kilom=10000 ##Variable iniciadora
    for elemento in camin:
        for nueva in matriz.columns:
            if nueva not in camin:
                    kil=matriz.at[elemento,nueva]
                    if kil+distancia_acumulada[elemento]<kilom:
                        distancia_acumulada[nueva]=kil+distancia_acumulada[elemento]
                        kilom=kil+distancia_acumulada[elemento]
                        elem=elemento
                        nuev = nueva
    camin.append(nuev)
    camino.append([elem, nuev])
for montana in matriz.columns:
     total+=distancia_acumulada[montana]
         
print("El camino sería:",camin,f"y por tanto haríamos {len(camin)} paradas")
print("El árbol centrado en Alicante sería:", *camino)
print("La distancia total de ese árbol mínimo sería de:",total,"km")

El camino sería: ['Alicante', 'Sierra de Fontcalent', 'Ermita de Orito', "Cabeco d'Or", 'Peña Migjorn', 'Maigmo', 'El Cid', 'El Picacho', 'Puig Campana', 'Aitana', 'El Reconco', 'Ponoig', 'El Menejador', 'Mallada del Llop', 'Sierra Helada', 'Pla de la Casa', 'Cruz de Callosa', 'La Muela', 'Bernia', 'Montcabrer', 'Sierra de Olta', 'Peñon de Ifach', 'Sierra de Segaria', 'El Montgo'] y por tanto haríamos 24 paradas
El árbol centrado en Alicante sería: ['Alicante', 'Sierra de Fontcalent'] ['Sierra de Fontcalent', 'Ermita de Orito'] ['Alicante', "Cabeco d'Or"] ['Alicante', 'Peña Migjorn'] ['Alicante', 'Maigmo'] ['Ermita de Orito', 'El Cid'] ['Ermita de Orito', 'El Picacho'] ['Alicante', 'Puig Campana'] ["Cabeco d'Or", 'Aitana'] ['Maigmo', 'El Reconco'] ['Puig Campana', 'Ponoig'] ['Peña Migjorn', 'El Menejador'] ['Aitana', 'Mallada del Llop'] ['Alicante', 'Sierra Helada'] ['Aitana', 'Pla de la Casa'] ['Alicante', 'Cruz de Callosa'] ['Cruz de Callosa', 'La Muela'] ['Ponoig', 'Bernia'] ['El Menejador', 'Montcabrer'] ['Ponoig', 'Sierra de Olta'] ['Sierra de Olta', 'Peñon de Ifach'] ['Mallada del Llop', 'Sierra de Segaria'] ['Sierra de Segaria', 'El Montgo']
La distancia total de ese árbol mínimo sería de: 1046.6 km

# **Camino más rápido por Backtracking**

In [25]:
cami=["Confrides"]
caminaco=0 #Ayuda a establecer una condición para que se creen los caminos
kilometros=distancia_acumulada[ciudad]
while caminaco==0:
    c=0
    while c!=None:    
        c=None
        for elemento in camino:
            if elemento[1]==cami[-1]:
                cami.append(elemento[0])
                camino.remove(elemento)
                c=elemento
            elif elemento[0]==cami[-1]:
                cami.append(elemento[1])
                camino.remove(elemento)
                c=elemento
    if cami[-1]!="Balcón de Alicante":
        cami.pop() #Elimino la ultima ciudad del camino creado
    elif cami[-1]=="Balcón de Alicante":
        caminaco=1
cami.reverse()
print("Las paradas a realizar son:",cami)

Las paradas a realizar son: ['Balcón de Alicante', 'Maigmó', 'La Carrasqueta', 'Benifallim', 'Aitana (Tudons)', 'Confrides']

# Representar el mapa interactivo de las conexiones

In [ ]:

##Primero agrego un diccionario con los nombres de las localizaciones y sus coordenadas en latitud/longitud
coordenadas= {
    "Aitana (Tudons)": [38.6482, -0.2642], # Paso de la CV-770 (Correcto)
    "La Carrasqueta": [38.5866, -0.5042],  # Mirador/Paso superior CV-800
    "Benifallim": [38.6536, -0.3958],      # Puerto de Benifallim CV-785
    "Confrides": [38.6830, -0.2670],       # Puerto de Confrides CV-70
    "El Canalís": [38.6822, -0.6725],      # Paso de Onil a Bañeres
    "Torremanzanas": [38.5847, -0.4192],   # Puerto de Benifallim/Torremanzanas
    "Tibi": [38.5303, -0.5978],            # Puerto de Tibi
    "Coll de Rates": [38.7249,-0.0764],   # Cima de la carretera CV-715
    "Val de Ebo": [38.8058, -0.1589],      # Puerto de Ebo
    "Tàrbena": [38.6942, -0.1222],         # Coll de Sa Creueta (Tàrbena)
    "Miserat": [38.8332,-0.1531],         # Acceso por carretera (no la antena cima)
    "Sierra de Bernia": [38.6210, -0.0450],# Casas de Bernia (donde termina el asfalto)
    "Cumbre del Sol": [38.7180, 0.1520],   # Parking superior (Puig Llorença)
    "Cap de la Nau": [38.7300, 0.2200],    # Final de la carretera del Faro
    "Guadalest": [38.6767, -0.1983],       # Paso del pueblo/embalse
    "Monte Pego": [38.8250, -0.0620],      # Cima de la urbanización
    "Xorret de Catí": [38.5285, -0.6869],  # Paso de la cresta (Escalinata)
    "El Reconco": [38.6186, -0.7383],      # Final del asfalto junto a antenas
    "Port de l'Albiol": [38.6756, -0.4439],# Alto de l'Albiol
    "Puerto de Biar": [38.6294, -0.7658],  # CV-799
    "Font Roja": [38.6608, -0.5372],       # Santuario (final de carretera)
    "Font de Partegat": [38.6574,-0.2446],        
    "Oronet (Alicante)": [38.5642, -0.2458],# Alto de Finestrat/Sella
    "Puig Campana": [38.5830, -0.2150],    # Font del Molí (Base accesible) *
    "Tollos": [38.7561, -0.2747],          # Puerto de Tollos
    "Balcón de Alicante": [38.4983, -0.6289],# Área recreativa (carretera)
    "Maigmó": [38.4833, -0.6167],          # Aparcamiento Maigmó
    "Hoya de la Carrasca": [38.6850, -0.2950], # Paso montaña
    "Vall d'Alcalà": [38.7944, -0.2458],   # Puerto de Margarida/Alcalà
    "El Picacho": [38.2610, -0.8870]       # Puerto de la Pila (carretera)
}
# 2. Crear el mapa base
m = folium.Map(location=[38.3453,-0.4831], zoom_start=6)

# 3. Dibujar los puntos (nodos)
for ciudad in camin:
    folium.Marker(
        location=coordenadas[ciudad],
        popup=ciudad,
        icon=folium.Icon(color="green", icon="cloud")
    ).add_to(m)

# 4. DIBUJAR EL ÁRBOL (Las conexiones de tu variable 'camino')
# Tu variable 'camino' tiene este formato: [['Alicante', 'Valencia'], ['Valencia', 'Madrid'], ...]
for par in camino:
    ciudad_origen = par[0]
    ciudad_destino = par[1]
    
    # Extraemos las coordenadas de los dos puntos de esa conexión
    puntos_conexion = [coordenadas[ciudad_origen], coordenadas[ciudad_destino]]
    
    # Dibujamos la línea que une ese par específico
    folium.PolyLine(
        locations=puntos_conexion,
        color="red",
        weight=3,
        opacity=0.8,
        tooltip=f"Conexión: {ciudad_origen} - {ciudad_destino}"
    ).add_to(m)

# Guardar y ver
m.save("camino_mas_corto_Balcon.html")